collision_monitor:
  ros__parameters:
    use_sim_time: false
    base_frame_id: base_footprint
    odom_frame_id: odom
    cmd_vel_in_topic: /cmd_vel_smoothed
    cmd_vel_out_topic: /cmd_vel_safe
    state_topic: /romo_b/collision_monitor_state
    transform_tolerance: 0.2
    source_timeout: 0.20
    base_shift_correction: true
    stop_pub_timeout: 0.20
    polygons: [StopZone, SlowdownZone]
    StopZone:
      type: polygon
      points: [0.30, 0.38, 0.90, 0.38, 0.90, -0.38, 0.30, -0.38]
      action_type: stop
      max_points: 2
      visualize: true
      polygon_pub_topic: /romo_b/stop_zone
      enabled: true
    SlowdownZone:
      type: polygon
      points: [0.25, 0.65, 1.50, 0.65, 1.50, -0.65, 0.25, -0.65]
      action_type: slowdown
      slowdown_ratio: 0.30
      max_points: 2
      visualize: true
      polygon_pub_topic: /romo_b/slowdown_zone
      enabled: true
    observation_sources: [pointcloud]
    pointcloud:
      type: pointcloud
      topic: /sensing/lidar/top/pointcloud_filtered
      min_height: 0.10
      max_height: 1.80
      enabled: true
